version: "3"


services:
  postgres:
    image: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    # адрес файла, где хранятся переменные окружения
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=AdminAex070590
      - POSTGRES_DB=postgres_bd
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env
    shm_size: 4g

  web:
    image: alexanderpronikov/t_web_app:latest
    restart: always
    command: /entrypoint.sh

    ports:
      - "8000:8000"
    # "зависит от",
    volumes:
      # Контейнер web будет работать с данными, хранящиеся в томе static_value
      # через свою директорию /code/static/
      - static_value:/code/static/
      # Данные, хранящиеся в томе media_value,будут доступны в контейнере web
      # через директорию /code/media/
      - media_value:/code/media/
    depends_on:
      - postgres
    env_file:
      - ./.env


  nginx:
    image: nginx:alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx_prod/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./ssl:/etc/ssl

    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value: