# Generated by Django 4.0.4 on 2022-05-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='пользователь')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
            ],
        ),
    ]
